version: '3.8'

services:
  blockmesh-cli:
    image: dknodes/blockmesh-cli_x86_64:latest
    container_name: blockmesh-cli
    environment:
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
    restart: unless-stopped
